spring:
  application:
    name: recruiter-service
  datasource:
    url: jdbc:postgresql://localhost:5432/recruiterdb
    username: postgres
    password: root@root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  host: localhost
  port: 5672
